services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE "banco-stocker" WITH OWNER = postgres ENCODING = 'UTF8'  CONNECTION LIMIT = -1;'
- psql -U postgres -d banco-stocker -f banco/tabela.sql

before_install:
    - wget --no-check-certificate https://downloads.apache.org//ant/binaries/apache-ant-1.10.9-bin.tar.gz
    - tar -xzvf apache-ant-1.10.9-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.9/bin:$PATH
    - echo $(ant -version)

language: java

deploy:
  provider: heroku
  app: stocker-grupo3
  edge: true
  on:
    repo: jvitorgf/stocker-grupo3
jdk:
 - openjdk11

sudo: false
