
before_install:
    - wget --no-check-certificate https://downloads.apache.org//ant/binaries/apache-ant-1.10.8-bin.tar.gz
    - tar -xzvf apache-ant-1.10.8-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.8/bin:$PATH
    - echo $(ant -version)

language: java

jdk:
 - openjdk11

sudo: false
